config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :klasses
  resources :courses
  resources :professors
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :set_klass, only: [:show, :edit, :update, :destroy]

  # GET /klasses
  # GET /klasses.json
  def index
    @klasses = Klass.all
  end

  # GET /klasses/1
  # GET /klasses/1.json
  def show
  end

  # GET /klasses/new
  def new
    @klass = Klass.new
  end

  # GET /klasses/1/edit
  def edit
  end

  # POST /klasses
  # POST /klasses.json
  def create
    @klass = Klass.new(klass_params)

    respond_to do |format|
      if @klass.save
        format.html { redirect_to @klass, notice: 'Klass was successfully created.' }
        format.json { render :show, status: :created, location: @klass }
      else
        format.html { render :new }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klasses/1
  # PATCH/PUT /klasses/1.json
  def update
    respond_to do |format|
      if @klass.update(klass_params)
        format.html { redirect_to @klass, notice: 'Klass was successfully updated.' }
        format.json { render :show, status: :ok, location: @klass }
      else
        format.html { render :edit }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klasses/1
  # DELETE /klasses/1.json
  def destroy
    @klass.destroy
    respond_to do |format|
      format.html { redirect_to klasses_url, notice: 'Klass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klass
      @klass = Klass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klass_params
      params.require(:klass).permit(:term, :course_id, :professor_id)
    end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_form.html.erb
<%= form_with(model: klass, local: true) do |form| %>
  <% if klass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(klass.errors.count, "error") %> prohibited this klass from being saved:</h2>

      <ul>
      <% klass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :term %>
    <%= form.text_field :term %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%= form.number_field :professor_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/klasses/edit.html.erb
<h1>Editing Klass</h1>

<%= render 'form', klass: @klass %>

<%= link_to 'Show', @klass %> |
<%= link_to 'Back', klasses_path %>

app/views/klasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Klasses</h1>

<table>
  <thead>
    <tr>
      <th>Term</th>
      <th>Course</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @klasses.each do |klass| %>
      <tr>
        <td><%= klass.term %></td>
        <td><%= klass.course_id %></td>
        <td><%= klass.professor_id %></td>
        <td><%= link_to 'Show', klass %></td>
        <td><%= link_to 'Edit', edit_klass_path(klass) %></td>
        <td><%= link_to 'Destroy', klass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Klass', new_klass_path %>

app/views/klasses/new.html.erb
<h1>New Klass</h1>

<%= render 'form', klass: @klass %>

<%= link_to 'Back', klasses_path %>

app/views/klasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @klass.term %>
</p>

<p>
  <strong>Course:</strong>
  <%= @klass.course_id %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @klass.professor_id %>
</p>

<%= link_to 'Edit', edit_klass_path(@klass) %> |
<%= link_to 'Back', klasses_path %>